
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 07 16:35:55 CEST 2014
//----------------------------------------------------

package dataengine;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENT = 13;
  public static final int OP_BRAC = 7;
  public static final int QUOT = 2;
  public static final int CL_PAR = 4;
  public static final int OP_SBRAC = 5;
  public static final int NUMBER = 14;
  public static final int CL_SBRAC = 6;
  public static final int TRUE = 11;
  public static final int CL_BRAC = 8;
  public static final int EQUAL = 9;
  public static final int STRING = 15;
  public static final int EOF = 0;
  public static final int FALSE = 12;
  public static final int error = 1;
  public static final int SEMICOLON = 10;
  public static final int OP_PAR = 3;
}

